### ISSUE TITLE
GET_SINGLE preprocessor instance_id is Boolean instead of an Integer

### ISSUE THREAD

**Issue by cryarchy** [jfinkels/flask-restless#539] opened 2016-05-28 06:52 UTC
I'm using Flask-Restless==0.17.0 and I receive a *Boolean instance_id* to my **GET_SINGLE** preprocessors. i.e; when I visit an example URL `http://localhost:5000/api/account/3` the preprocessor function:
```python
def get_show_id(instance_id=None, **kwargs):
    print (instance_id)
```

prints out `True`. Also, all **GET_SINGLE** URLs point to the same single record in my database.

**Comment by jfinkels** [comment] 2016-06-06 03:54
Thanks for the report. Can you please provide a minimal working example demonstrating this behavior so I can determine where the issue is?

**Comment by jfinkels** [comment] 2016-10-06 02:41
Closing due to lack of information.

**Closed by jfinkels** 2016-10-06 02:41 UTC
