### ISSUE TITLE
Flask-Restless doesn't follow JSON API filtering recommendation

### ISSUE THREAD

**Issue by fhals** [jfinkels/flask-restless#492] opened 2016-02-25 02:34 UTC
I'm using the filtering format from [JSON API recommendations][1] like this:

    ?filter[author]=12

But in flask-restless the format is

    ?filter[objects]=[{"name":"author","op":"eq","val":12}]

How can flask-restless compromise this difference?

[1]: http://jsonapi.org/recommendations/#filtering

**Comment by jfinkels** [comment] 2016-02-26 02:30
You are right that our current filtering strategy does not match the recommendations by JSON API. This is because the filtering behavior in Flask-Restless was designed long before JSON API solidified its current recommendation for filtering.

It may be a good idea to also support this simpler form of filtering by field (i.e. by attribute or relationship). It seems the idea is that if the string between the brackets is a relationship, then the value (after the equals sign) should be an ID, or a comma-separated list of IDs. The recommendation doesn't say anything about filtering by attribute values, but I imagine the idea is the same: if I do `GET /people?filter[name]=foo`, then the response should include only a list of person resources whose `name` attribute matches the given value `foo`.

It seems possible to support *both* forms, as long as a resource does not have an attribute or relationship named "objects". I'm marking this as a request for an enhancement.

**Comment by fhals** [comment] 2016-02-26 13:26
And another recommendation include [naming](http://jsonapi.org/recommendations/#naming) that maybe need to be addressed.

**Comment by jfinkels** [comment] 2016-02-26 15:28
For that different recommendation, please open another issue.

**Comment by fhals** [comment] 2016-03-01 15:39
OK. reciting from the recommendation

> The base specification is agnostic about filtering strategies supported by a server. The filter query parameter is reserved to be used as the basis for any filtering strategy.

Actually  I don't have any idea if we use this recommendation to filter attributes using OR clause, do you? I propose to convert any request filter which is using json api recommendation to current format, since the current format can include json api filtering recommendation format but not vice versa.

Maybe it should has checking feature to check which format the "objects" using?

**Comment by jfinkels** [comment] 2016-03-01 15:51
@fhals wrote:

> Actually  I don't have any idea if we use this recommendation to filter attributes using OR clause, do you?

They don't specify in the recommendation, but I imagine the request

```http
GET /comments?filter[post]=1,2&filter[author]=12 HTTP/1.1
```

would fetch only those comments on posts 1 or 2 AND having author 12. This matches most other searching facilities.

> I propose to convert any request filter which is using json api recommendation to current format, since the current format can include json api filtering recommendation format but not vice versa.

That's probably the best implementation: convert the simpler filter query parameters into the more complicated "filter objects" since the latter are more general. That seems to be the implementation you proposed in pull request #494.

> Maybe it should has checking feature to check which format the "objects" using?

We should be able to tell pretty quickly: if the query parameter is `filter[objects]` or `filter[somethingelse]`.

**Comment by jfinkels** [comment] 2016-05-03 05:27
I implemented this in pull request #523.

**Closed by jfinkels** 2016-05-03 05:27 UTC
Labels: enhancement
