### ISSUE TITLE
API routes 404 behind everything but Flask Development Server

### ISSUE THREAD

**Issue by frankV** [jfinkels/flask-restless#433] opened 2015-05-01 16:26 UTC
I can't figure this out, and I've tried it with both gunicorn and uwsgi!

If I run the app with the flask development server (and this happens both locally and deployed), the routes registered by apiManager are fine, but if I use anything else (e.g.: gunicorn or uwsgi) they 404?

I found that the headers of the request are different between the two cases:
```
# gunicorn
$ curl http://localhost:8000/api/v1/products -i -H 'Accept: application/json'
HTTP/1.1 404 NOT FOUND
Server: gunicorn/19.3.0
Date: Fri, 01 May 2015 03:12:18 GMT
Connection: close
Content-Type: application/json
Content-Length: 87


# flask dev server
$ curl http://localhost:8000/api/v1/products -i -H 'Accept: application/json'
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 3854
Link: <http://hydra.local:8000/api/v1/products?page=1&results_per_page=10>; rel="last"
Link: <http://hydra.local:8000/api/v1/products?page=1&results_per_page=10>; rel="last"
Vary: Accept
Content-Type: application/json
Server: Werkzeug/0.9.6 Python/2.7.6
Date: Fri, 01 May 2015 03:10:45 GMT
```

**Comment by jonafato** [comment] 2015-06-21 05:05
@frankV How are you running your application behind Gunicorn and uwsgi? This is likely a configuration issue rather than a Flask-Restless one. If it is a bug in Flask-Restless, steps to reproduce (a minimal example illustrating the issue) would be needed to get it fixed.

**Comment by jfinkels** [comment] 2016-02-04 09:18
I suspect this is not a Flask-Restless issue directly, though if it has anything to do with Flask-Restless, it would be helpful to add a note in the documentation. If you do find anything that you think may help others with configuration of their servers, please let us know. In the meantime, I'm closing this issue for lack of evidence.

**Closed by jfinkels** 2016-02-04 09:18 UTC

**Comment by Dalton-Hill** [comment] 2018-03-13 19:05
In case anyone else runs into a similar issue...

I was experiencing something like this as well. This was due to having my "APIManager" initialized within the standard "if __name__ ==  '__main__':" block.

Example of the incorrect code.
`
if __name__ == '__main__':
    manager = flask_restless.APIManager(app, flask_sqlalchemy_db=db)
    manager.create_api(District, methods=['GET', 'PATCH', 'POST', 'DELETE'])
    manager.create_api(Status, methods=['GET', 'PATCH', 'POST', 'DELETE'])
    manager.create_api(Updates, methods=['GET', 'PATCH', 'POST', 'DELETE'])
`

To fix, I just pulled the "manager." lines out of the IF block.

**Comment by jonrcable** [comment] 2019-07-11 19:05
thank you, this post saved me. i'm still not entirely sure why this is the case but it works. developing with the internal Flask server was fine, but when moving it to a production CentOS server with gunicorn/nginx all the routes came back 404 . I realized it was a route issue when i noticed the css/js files in /static served correctly but the 'virtual' routes/blueprints were not working. 

I'd still like to know why that needs to be abstracted from the __name__ function. 

# (development) app.py - only works with Flask server
if __name__ == "__main__":
    create = create_app()
    app = register_app(create)

    app.run(host='0.0.0.0', port=5000, debug=True)

# (working) wsgi.py - working with gunicorn and nginx via unix socket
# these need to be called before the app gets init
create = create_app()
app = register_app(create)

# now we can init the app
if __name__ == "__main__":

    app.run(host='0.0.0.0', port=8000)
