### ISSUE TITLE
Specifying url_prefix on top level

### ISSUE THREAD

**Issue by hussaintamboli** [jfinkels/flask-restless#430] opened 2015-04-22 13:47 UTC
I want to avoid repetition of specifying url_prefix in each API that I create

    e.g.
    manager = flask.ext.restless.APIManager(app, flask_sqlalchemy_db=models.db)
    manager.create_api(models.Teacher, methods=['GET', 'POST'], url_prefix='/api/v1')
    manager.create_api(models.Student, methods=['GET', 'POST'], url_prefix='/api/v1')

Is there any way of providing `url_prefix` at the top? I didn't see it in `help(APIManager)`.

**Comment by elvis-macak** [comment] 2015-04-28 15:55
I think this will help you
<pre>
from functools import partial
...
Manager.create_api = partial(manager.create_api, url_prefix='/api/v1')
</pre>

**Comment by hussaintamboli** [comment] 2015-04-29 06:35
I had started using something like

    def _create_api(*args, **kwargs):
        # create api at a different prefix
        if 'url_prefix' not in kwargs:
            kwargs['url_prefix'] = '/api/v1'

    def create_api(app):
        global manager
        manager = flask.ext.restless.APIManager(app, flask_sqlalchemy_db=db)
        _create_api(models.Teacher, methods=['GET', 'POST'])
        _create_api(models.Student, methods=['GET', 'POST'])

But your way clearly seems more subtle and clean.

Don't you think that it would be better to have it at the top in the `APIManager` call itself?

**Comment by elvis-macak** [comment] 2015-04-30 06:30
yeah, i also think it need to expose an parameter in the __init__ method, and i commit it as a patch  https://github.com/jfinkels/flask-restless/pull/431/commits

**Comment by jonafato** [comment] 2015-06-21 05:14
This seems like a duplicate of #426.

**Closed** 2015-06-22 09:00 UTC
