### ISSUE TITLE
quickstart.py no response

### ISSUE THREAD

**Issue by kirkins** [jfinkels/flask-restless#564] opened 2016-08-07 01:11 UTC
I have quickstart.py running with no errors but requests just hang forever.

When I run the curl.sh file it gets stuck at "Making an initial GET request"

**Comment by kirkins** [comment] 2016-08-07 01:31
When I stop running flask I get a traceback

`Traceback (most recent call last):
  File "/home/heimer/Documents/code/flaskr/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/flask/cli.py", line 478, in main
    cli.main(args=args, prog_name=name)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/flask/cli.py", line 403, in run_command
    use_debugger=debugger, threaded=with_threads)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 550, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 462, in __init__
    socket.SOCK_STREAM)
socket.error: [Errno 9] Bad file descriptor
127.0.0.1 - - [06/Aug/2016 21:29:48] "GET /api/person HTTP/1.1" 200 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/home/heimer/Documents/code/flaskr/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 152, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
`

**Comment by jfinkels** [comment] 2016-08-15 02:55
There doesn't seem to be any Flask-Restless code in the traceback you posted in your second comment. In fact, maybe the issue was caused by some other code; it seems you are using the Flask tutorial project?

In order to ensure this is a problem with Flask-Restless, can you please test the version of the code from the current `master` branch in a fresh virtual environment with nothing else installed? Something like the following will checkout the most recent development version of Flask-Restless, create and activate a virtual environment, install the runtime dependencies, and start the example server:
```sh
git clone https://github.com/jfinkels/flask-restless.git
cd flask-restless
virtualenv venv
. venv/bin/activate
pip install -r requirements.txt
python examples/quickstart.py
```

**Comment by jfinkels** [comment] 2016-09-16 03:05
Closing this due to lack of information. If you can narrow this down to a problem in Flask-Restless, please reopen this issue or create a new one.

**Closed by jfinkels** 2016-09-16 03:05 UTC
