### ISSUE TITLE
The create_api method fails if flask-sqlalchemy has been initialized with init_app()

### ISSUE THREAD

**Issue by TimotheeJeannin** [jfinkels/flask-restless#409] opened 2015-02-24 08:59 UTC
Let's say I have two files:
    
**server.py**
```python
import flask
import flask.ext.sqlalchemy
import flask.ext.restless
from model import db, Person, Computer

app = flask.Flask(__name__)
app.config['DEBUG'] = True
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'

with app.app_context():
    db.init_app(app)
    db.drop_all()
    db.create_all()

manager = flask.ext.restless.APIManager(app, flask_sqlalchemy_db=db)
manager.create_api(Person, methods=['GET', 'POST', 'DELETE'])
manager.create_api(Computer, methods=['GET'])

app.run()
```

**model.py**
```python
import flask.ext.sqlalchemy

db = flask.ext.sqlalchemy.SQLAlchemy()


class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode, unique=True)
    birth_date = db.Column(db.Date)


class Computer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode, unique=True)
    vendor = db.Column(db.Unicode)
    purchase_time = db.Column(db.DateTime)
    owner_id = db.Column(db.Integer, db.ForeignKey('person.id'))
    owner = db.relationship('Person', backref=db.backref('computers',
                                                         lazy='dynamic'))
```

When I do a `python server.py` **it works as expected with Flask-Restless version `0.16.0`**, but **fails with Flask-Restless version `0.17.0`**.

    Traceback (most recent call last):
      File "server.py", line 16, in <module>
        manager.create_api(Person, methods=['GET', 'POST', 'DELETE'])
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/flask_restless/manager.py", line 698, in create_api
        blueprint = self.create_api_blueprint(app=app, *args, **kw)
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/flask_restless/manager.py", line 566, in create_api_blueprint
        pk_name = primary_key or primary_key_name(model)
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/flask_restless/helpers.py", line 232, in primary_key_name
        pk_names = primary_key_names(model)
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/flask_restless/helpers.py", line 214, in primary_key_names
        return [key for key, field in inspect.getmembers(model)
      File "/usr/lib/python2.7/inspect.py", line 253, in getmembers
        value = getattr(object, key)
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 454, in __get__
        return type.query_class(mapper, session=self.sa.session())
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 71, in __call__
        return self.registry()
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 878, in __call__
        return self.registry.setdefault(key, self.createfunc())
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 704, in create_session
        return SignallingSession(self, **options)
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 149, in __init__
        self.app = db.get_app()
      File "/home/tim/Workspace/testRestless/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 845, in get_app
        raise RuntimeError('application not registered on db '
    RuntimeError: application not registered on db instance and no application bound to current context

**Comment by pplanel** [comment] 2015-06-08 22:45
Version 0.17.0 confirmed here, downgraded to 0.16.0 and worked.

**Comment by diegoponciano** [comment] 2015-06-08 23:42
I've got the same problem with 0.17.0, although I didn't try it with 0.16.0

**Comment by nickjbyrne** [comment] 2015-06-14 13:53
Downgrade to 0.16 worked for me

**Comment by darrenburns** [comment] 2015-06-28 14:42
Same issue. Seems to work with fine if only using `GET` for me, as soon as I add `POST` to the methods it throws this error.

**Comment by darrenburns** [comment] 2015-06-28 14:54
In 0.17 you can pass your app as a keyword argument to `create_api()` and remove it from the constructor of `APIManager()`. The following should work (although inconvenient):

```python
rest_manager = APIManager(flask_sqlalchemy_db=db)
rest_manager.create_api(SomeModel, methods=['GET', 'POST'], app=app)
```

**Comment by joergwork** [comment] 2015-08-19 16:37
Same issue.
I tried the following and succeeded but can't explain why:

``` 
with app.app_context():
    rest_manager.create_api(SomeModel, methods=['GET', 'POST'])
```

**Comment by Meph-** [comment] 2015-08-20 05:29
I added next line
    db.app = app
before
    db.init_app(app)
and restless works.

**Comment by green4984** [comment] 2016-01-15 04:08
finally, I found what it happened!

this is below with create_api is ok for me

```python
manager.create_api(Person, methods=['GET', 'POST', 'DELETE'], primary_key='id')
```

I discover the source code of create_api_blueprint, add a primary_key will not check the db before
app context

**Comment by jfinkels** [comment] 2016-02-04 08:21
Hi all,

The `init_app` and Flask application registration was totally crazy before, since I had no idea what I was doing. It should be fixed now (in the development version). I apologize for that. Closing this now, but please reopen a new issue if you still have problems (since I completely rewrote the code).

**Closed by jfinkels** 2016-02-04 08:21 UTC

**Comment by sammarxz** [comment] 2017-08-08 23:33
Check if any route in your app
