### ISSUE TITLE
[1.0.0b] GET request errors without disabling headers

### ISSUE THREAD

**Issue by 2Cubed** [jfinkels/flask-restless#547] opened 2016-06-10 23:52 UTC
Using the [quickstart example](https://github.com/jfinkels/flask-restless/blob/master/examples/quickstart.py) with v1.1.0b, I am unable to get data without explicitly disabling headers in my request. (I get a 406 otherwise.)

The following attempts, which I would expect to work, receive 406 errors.
```python
from requests import get
get("http://localhost:5000/api/person").json()
```
```bash
curl http://localhost:5000/api/person
```

These, however, will work, retrieving the correct content.
```python
from requests import get
get("http://localhost:5000/api/person", headers=False).json()
```
```python
from requests import get
get("http://localhost:5000/api/person", headers='').json()
```
```python
from requests import get
get("http://localhost:5000/api/person", headers=()).json()
```
```python
from requests import get
get("http://localhost:5000/api/person", headers=[]).json()
```

Although these will not, returning a 406 error.
```python
from requests import get
get("http://localhost:5000/api/person", headers=None).json()
```
```python
from requests import get
get("http://localhost:5000/api/person", headers={}).json()
```

Finally, the 406 error is given as follows, with `code`, `id`, `links`, `meta`, `source`, and `title` set to `null` rather than the values they should be, as outlined in [the JSON API specifications](http://jsonapi.org/format/#errors).
```json
{
  "errors": [
    {
      "code": null, 
      "detail": "Accept header, if specified, must be the JSON API media type: application/vnd.api+json", 
      "id": null, 
      "links": null, 
      "meta": null, 
      "source": null, 
      "status": 406, 
      "title": null
    }
  ], 
  "jsonapi": {
    "version": "1.0"
  }, 
  "meta": {}
}
```

**Comment by jfinkels** [comment] 2016-06-16 03:00
Thanks for researching this! Let's go through these one at a time.

> The following attempts, which I would expect to work, receive 406 errors.
> ```python
> from requests import get
> get("http://localhost:5000/api/person").json()
> ```

It seems that the requests library automatically inserts an `Accept: */*` header into `GET` requests; see the *[Requests and Responses][1]* section of their documentation. This is a bug in Flask-Restless: my reading of the relevant RFC makes me think that `Accept: */*` and `Accept: application/*` should cause the server to proceed as normal.

I have opened issue #548 for this.

[1]: http://docs.python-requests.org/en/latest/user/advanced/#request-and-response-objects

> ```bash
> curl http://localhost:5000/api/person
> ```

The same thing is happening here: curl automatically inserts `Accept: */*`, so the same comments as above apply. 


> These, however, will work, retrieving the correct content.
> ```python
> from requests import get
> get("http://localhost:5000/api/person", headers=False).json()
> ```

This request has no headers, so the server processes it as normal (the `Accept: application/vnd.api+json` header is not required by JSON API). This is not a bug.

The same goes for setting `headers` to be the empty string, the empty tuple, and the empty list.

> Although these will not, returning a 406 error.
> ```python
> from requests import get
> get("http://localhost:5000/api/person", headers=None).json()
> ```

I'm guessing the default value for `headers` is already `None`, so doing this just puts you in the first case (i.e., as if you had called `get()` with no keyword arguments).

> ```python
> from requests import get
> get("http://localhost:5000/api/person", headers={}).json()
> ```

For some reason, `requests` interprets the empty dictionary as indicating that the user has requested no headers to be set. Therefore it automatically inserts the `Accept: */*` header, as in the first case above. If you consider this a bug, it is a bug with `requests`, not with Flask-Restless.

> Finally, the 406 error is given as follows, with `code`, `id`, `links`, `meta`, `source`, and `title` set to `null` rather than the values they should be, as outlined in [the JSON API specifications](http://jsonapi.org/format/#errors). [...]

This is definitely a bug, but it is a separate issue. I have opened issue #549 for this.

I'm going to close this issue as it is really two issues. Please continue the discussion on either #548 or #549.

**Closed by jfinkels** 2016-06-16 03:00 UTC

**Comment by 2Cubed** [comment] 2016-06-16 06:08
@jfinkels: Sorry for only opening one issue; my mistake. Thank you for correcting it. 🙂
